// client/src/react/components/LabeledInput.js
import React from "react";
import Label from "./Label";

export default ({ id, label, value, handleChange, type = "text", ...rest }) => {
  return (
    <div>
      <Label htmlFor={id}>{label}</Label>
      <input
        id={id}
        type={type}
        value={value}
        onChange={handleChange(id)}
        {...rest}
      />
    </div>
  );
};

// client/src/svelte/components/LabeledInput.svelte
<script>
  import Label from "./Label.svelte";

  export let id;
  export let label;
  export let value;
  export let handleChange;
</script>

<div class="form-group">
  <Label for={id}>{label}</Label>
  <input type="text" {id} value={value || ''} on:change={handleChange(id)} />
</div>
