// client/src/react/NavigationContainer.js
import React, { useState, useEffect } from "react";
import styled from "styled-components";
import { Switch, Route, withRouter } from "react-router-dom";
import Menu from "./Menu";
import PAGES from "./pages";
import HammerContainer from "./HammerContainer";

const StyledHammerContainer = styled(HammerContainer)`
  height: 100%;
  width: 100%;
`;

const getNextPage = (pages, pathname, direction) => {
  const i = pages.findIndex(page => page.path === pathname);
  let index = i + direction;
  if (index > pages.length - 1) {
    index = 0;
  }
  if (index < 0) {
    index = pages.length - 1;
  }
  return pages[index].path;
};

const NavigationContainer = ({ history, location }) => {
  const [desiredPage, setDesiredPage] = useState(0);

  useEffect(() => {
    if (desiredPage === 1 || desiredPage === -1) {
      history.push(getNextPage(PAGES, location.pathname, desiredPage));
      setDesiredPage(0);
    }
  }, [desiredPage]);

  const options = {
    onSwipeLeft: () => {
      setDesiredPage(1);
    },
    onSwipeRight: () => {
      setDesiredPage(-1);
    }
  };

  return (
    <StyledHammerContainer options={options}>
      <Menu />
      <main>
        <Switch>
          {PAGES.map(page => (
            <Route
              key={page.path}
              path={page.path}
              exact={true}
              component={page.component}
            />
          ))}
        </Switch>
      </main>
    </StyledHammerContainer>
  );
};

export default withRouter(NavigationContainer);

// client/src/svelte/NavigationContainer.svelte
<script>
  import Route from "svelte-router-spa/src/components/route.svelte";
  import { routeIsActive } from "svelte-router-spa";
  import { navigateTo } from "svelte-router-spa";
  import Menu from "./Menu.svelte";
  import HammerContainer from "./HammerContainer.svelte";
  import pages from "./pages";
  import { BASENAME } from "./routes";

  export let currentRoute;
  const params = {};

  $: activePage = null;

  const update = () => {
    pages.forEach((page, i) => {
      if (routeIsActive(BASENAME + page.path)) {
        activePage = i;
      }
    });
  };

  $: {
    update();
  }

  const options = {
    onSwipeLeft: () => {
      let next = activePage + 1;
      if (next >= pages.length) {
        next = 0;
      }
      navigateTo(BASENAME + pages[next].path);
    },
    onSwipeRight: () => {
      let next = activePage - 1;
      if (next <= -1) {
        next = pages.length - 1;
      }
      navigateTo(BASENAME + pages[next].path);
    }
  };
</script>

<svelte:window on:locationchange={update} />

<HammerContainer {options}>
  <Menu />
  <main>
    <Route {currentRoute} {params} />
  </main>
</HammerContainer>
